name: Different Ways to trigger a workflow
# on: push # Here the workflow will be triggered on every push event to the repository, and it will to be all branch, as the branch is not specified
# on: ["push", "pull_request"] # Here the workflow will be triggered on both push and pull request events, and it will to be all branch, as the branch is not specified
on: 
  push:
    branches: 
    - main # Here the workflow will be triggered on every push event to the main branch of the repository 
    - dev # Here the workflow will be triggered on every push event to the dev branch of the repository
    - 'feature/**' # Here the workflow will be triggered on every push event to the branches which are starting with feature/ of the repository
# So, for the PR, lets see how to develop it, like we will raise a PR and then we will see that the workflow is getting triggered or not, and if it is getting triggered then we will see the logs of it as well, so lets do that now: 
  pull_request:
    branches: 
    - main # Here the workflow will be triggered on every pull request event to the main branch of the repository 
    - dev # Here the workflow will be triggered on every pull request event to the dev branch of the repository
    - 'feature/**' # Here the workflow will be triggered on every pull request event to the branches which are starting with feature/ of the repository

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "This workflow is triggered on push event"