name: Hello World  # Can be anything 
on: workflow_dispatch # Here when should the work flow get triggered, here workflow_dipatch is nothing but manually
jobs:  # In a workflow, we can have multiple jobs, but here we will have only one
  hello: # Here this is the name of the job, it can be again any random name
    runs-on: ubuntu-latest # Now this above job is supposed to run on some image, or machine right?
    steps:
      - name: Hello Step  # Once again any random name, and what step should it run, will be in the next line
        run: echo "Hello World" # So, here it will just echo/print out the statement thats it
      - name : Multiple Command
        run: | # So, here multiple command can be executed by usign the pipe command/symbol
          echo "This is the first message of multiple command execution"
          echo "This is the second message of multiple command execution"

  job-2: # Second job here
    runs-on: ubuntu-latest
    steps:
      - name: Build steps
        run: echo "A sample demo build"

  job-3: # Third job here
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "Just a test job"

  job-4: # $th job here
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy this application"

# So, earlier we created 4 jobs, and we saw that all of them were running  parallerly right? So, what if, I want to build first, then test, and then deploy so, it should follow some specific flow right? So, we will configure that now:


  job-5:
    runs-on: ubuntu-latest
    steps:
      - name: building phase
        run: echo "Build first here"
  job-6:
    runs-on: ubuntu-latest
    needs: job-5  # So, here as discussed earlier, we need some jobs to be done, before this job, so that we can see the sequential proper flow
    steps:
      - name: Unit testing phase
        run: echo "Unit testing here"
  job-7:
    runs-on: ubuntu-latest
    needs: job-6 # So, here as discussed earlier, we need some jobs to be done, before this job, so that we can see the sequential proper flow
    steps:
      - name: Deployment Phase
        run: echo "Deployment here"
  
